"""
Fusing different textual heuristics
to construct a richer context for the final prompt.
"""
import os
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sentence_transformers import SentenceTransformer

token = os.getenv("HUGGINGFACE_TOKEN")

# Initialize the encoder once (matches "open-source pipeline" goal [cite: 20])
encoder = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2', token=token) 

def apply_fusion_scoring(candidates, retrieved_examples, qa_caption, lambdas=(1.0, 0.5, 0.5)):
    """
    Re-ranks Prophet candidates based on QACap alignment.
    
    Parameters
    ----------
    candidates: List of dicts [{'answer': 'dog', 'score': 0.9, ...}] (from Prophet)
    retrieved_examples: List of strings (the text of examples Prophet found)
    qa_caption: String (your generated Question-Aware Caption)
    lambdas: Tuple of weights (lambda1, lambda2, lambda3) [cite: 79]
    """
    if not retrieved_examples:
        return candidates
    l1, l2, l3 = lambdas

    cap_emb = encoder.encode([qa_caption]) 
    ex_embs = encoder.encode(retrieved_examples)
    
    cap_ex_sims = cosine_similarity(cap_emb, ex_embs)[0]
    
    ranked_candidates = []
    
    avg_sim = np.mean(cap_ex_sims) if len(cap_ex_sims) > 0 else 0
    
    for i, cand in enumerate(candidates):
        s_j = cand.get('score', 0)
        sim_z_zi = cand.get('retrieval_sim', 0)
        
        sim_cap_zi = cap_ex_sims[i] if i < len(cap_ex_sims) else avg_sim
        
        new_score = (l1 * s_j) + (l2 * sim_z_zi) + (l3 * sim_cap_zi)
        
        cand_new = cand.copy()
        cand_new['fused_score'] = new_score
        ranked_candidates.append(cand_new)
        
    ranked_candidates.sort(key=lambda x: x['fused_score'], reverse=True)
    
    return ranked_candidates


def fuse_caption_with_heuristics(
    original_caption: str,
    qa_caption: str,
    strategy: str = 'prepend'
) -> str:
    """
    Fuses the original image caption with the question-aware caption.

    Parameters
    ----------
    original_caption : str
        The generic caption for the image.
    qa_caption : str
        The question-aware caption generated by QACap.
    strategy : str, optional
        The fusion strategy to use. Can be 'prepend', 'append', or 'replace'.
        By default 'prepend'.

    Returns
    -------
    str
        The fused caption string.
    """
    if not qa_caption:
        return original_caption

    if strategy == 'prepend':
        return f"Supporting information: {qa_caption}. {original_caption}"
    elif strategy == 'append':
        return f"{original_caption}. Supporting information: {qa_caption}"
    elif strategy == 'replace':
        return qa_caption
    else:
        # Default to original if strategy is unknown
        return original_caption
