"""
Fusing different textual heuristics
to construct a richer context for the final prompt.
"""

def fuse_caption_with_heuristics(
    original_caption: str,
    qa_caption: str,
    strategy: str = 'prepend'
) -> str:
    """
    Fuses the original image caption with the question-aware caption.

    Parameters
    ----------
    original_caption : str
        The generic caption for the image.
    qa_caption : str
        The question-aware caption generated by QACap.
    strategy : str, optional
        The fusion strategy to use. Can be 'prepend', 'append', or 'replace'.
        By default 'prepend'.

    Returns
    -------
    str
        The fused caption string.
    """
    if not qa_caption:
        return original_caption

    if strategy == 'prepend':
        return f"Supporting information: {qa_caption}. {original_caption}"
    elif strategy == 'append':
        return f"{original_caption}. Supporting information: {qa_caption}"
    elif strategy == 'replace':
        return qa_caption
    else:
        # Default to original if strategy is unknown
        return original_caption
